print("---Willkommen zum Geburtstagskarten-Generator---")
name = str(input("Name der zu grüßende Person eingeben: "))
age= int(input("Alter der zu grüßende Person eingeben: "))
sender = str(input("Eigenen Namen eingben: "))
print("Hallo", name)
print(f"ich wünsche dir alles gute zu deinem {age} ten Geburtstag.")
print("Ich hoffe, dass du einem schönen Tag hattest und mit deinen liebsten feiert.")
print("Zudem wünsche ich dir alles nur erdenklich Gute Wünsche für das neue Lebensjahr und viel Gesundheit!")
print("Liebe Grüße")
print(sender)